AWSTemplateFormatVersion: 2010-09-09

Description: Dictionary infrastructure

Resources:
  DictionaryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dictionary-bucket-862248740116

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  DictionaryArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dictionary-artifacts-862248740116

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  DictionaryTranslateLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DictionaryTranslateLambdaRole

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: LambdaAssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: DictionaryCloudWatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: WriteLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

        - PolicyName: DictionaryTranslateS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ListBucket
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt DictionaryBucket.Arn

              - Sid: ManageObjects
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub "${DictionaryBucket.Arn}/*"

        - PolicyName: DictionaryArtifactsS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ListBucket
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt DictionaryArtifactsBucket.Arn

              - Sid: ManageObjects
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "${DictionaryArtifactsBucket.Arn}/*"

  DictionaryTranslateLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/DictionaryTranslateLambda
      RetentionInDays: 30
